mysql:
  build: mysql
  env_file:
    - settings.env
  # volumes:
  #   - "data/backup:/backup"
  #   - "data/mysql:/var/lib/mysql"
  ports:
    - "3306"


vimbadmin:
  build: vimbadmin
  env_file:
    - settings.env
  ports:
    - "80:80"
  links:
    - mysql

# postfix:
#   build: postfix
#   ports:
#     - "25:25"
#     - "993:993"
#     - "587:587"
#   links:
#     - mysql
#     - dovecot

# dovecot:
#   build: dovecot
#   links:
#     - mysql

# roundcube:
#   build: roundcube
#   links:
#     - mysql

# memcache:
#   build: memcache