mysql:
  build: mysql
  env_file:
    - settings.env
  volumes:
    - "data/backup:/backup"
  #   - "data/mysql:/var/lib/mysql"
  ports:
    - "3306"

webserver:
  build: webserver
  env_file:
    - settings.env
  ports:
    - "80:80"
  links:
    - mysql
    - memcache

mail:
  build: mail
  env_file:
    - settings.env
  links:
    - mysql
    - opendkim
  volumes:
    - "data/certs:/etc/certs"

opendkim:
  build: opendkim
  env_file:
    - settings.env
  ports:
    - "8891"
  volumes:
    - "data/certs:/etc/certs"

memcache:
  build: memcache
  ports:
    - "11211"