mail:
  build: mail
  env_file:
    - settings.env
  links:
    - mysql
    - opendkim
  volumes:
    - "data/certs:/etc/certs"
  volumes_from:
    - storagebackup
  ports:
    - "587:587"
    - "993:993"
    - "995:995"

opendkim:
  build: opendkim
  env_file:
    - settings.env
  ports:
    - "8891"
  volumes:
    - "data/certs:/etc/certs"

# If you only want the mail server and no webmail/admin simply remove webserver and memcache
webserver:
  build: webserver
  env_file:
    - settings.env
  ports:
    - "80:80"
  volumes:
    - "data/certs:/etc/certs"
  volumes_from:
    - storagebackup
  links:
    - mysql
    - memcache
    - mail

memcache:
  build: memcache
  ports:
    - "11211"

mysql:
  build: mysql
  env_file:
    - settings.env
  volumes:
    - "data/backup:/backup"
  #   - "data/mysql:/var/lib/mysql"
  ports:
    - "3306"

# Storage container for vmail that also creates daily backups
storagebackup:
  build: storagebackup
  env_file:
    - settings.env
  links:
    - mysql
  volumes:
    - "/var/vmail"
    - "data/backup:/backup"