postfix:
  build: postfix
  ports:
    - "25:25"
    - "993:993"
    - "587:587"
  links:
    - mysql
    - dovecot
    - opendkim

dovecot:
  build: dovecot
  links:
    - mysql

opendkim:
  build: opendkim

vimbadmin:
  build: vimbadmin
  links:
    - mysql

roundcube:
  build: roundcube
  links:
    - mysql

mysql:
  build: mysql
  volumes:
    - "backup:/backup"
    - "mysql:/var/lib/mysql"
  ports:
    - "3306"

webserver:
  build: webserver
  ports:
    - "80:80"
  links:
    - vimbadmin
    - roundcube
